package com.github.edgar615.spring.consul.student;

import com.github.edgar615.util.db.Persistent;
import com.github.edgar615.util.db.PrimaryKey;
import com.github.edgar615.util.db.VirtualKey;
import com.google.common.base.MoreObjects;
import com.google.common.collect.Lists;
import com.google.common.collect.Maps;

import java.util.Date;
import java.util.List;
import java.util.Map;

/**
* This class is generated by Jdbc code generator.
*
* Table : user
* remarks: 
*
* @author Jdbc Code Generator Date 2020-12-30
*/
public class User implements Persistent<Long> {

    private static final long serialVersionUID = 1L;
    
    /**
    * Column : user_id
    * remarks: id
    * default: 
    * isNullable: false
    * isAutoInc: false
    * isPrimary: true
    * type: -5
    * size: 19
    */
    @PrimaryKey
    private Long userId;

    /**
    * Column : username
    * remarks: 
    * default: 
    * isNullable: true
    * isAutoInc: false
    * isPrimary: false
    * type: 12
    * size: 60
    */
    private String username;
    
    /**
    * Column : nickname
    * remarks: 
    * default: 
    * isNullable: true
    * isAutoInc: false
    * isPrimary: false
    * type: 12
    * size: 16
    */
    private String nickname;
    
    /**
    * Column : mobile
    * remarks: 
    * default: 
    * isNullable: true
    * isAutoInc: false
    * isPrimary: false
    * type: 12
    * size: 11
    */
    private String mobile;
    
    /**
    * Column : mail
    * remarks: 
    * default: 
    * isNullable: true
    * isAutoInc: false
    * isPrimary: false
    * type: 12
    * size: 60
    */
    private String mail;
    
    /**
    * Column : created_on
    * remarks: db
    * default: CURRENT_TIMESTAMP
    * isNullable: true
    * isAutoInc: false
    * isPrimary: false
    * type: 93
    * size: 26
    */
    @VirtualKey
    private Date createdOn;

    /**
    * Column : updated_on
    * remarks: db
    * default: CURRENT_TIMESTAMP
    * isNullable: true
    * isAutoInc: false
    * isPrimary: false
    * type: 93
    * size: 26
    */
    @VirtualKey
    private Date updatedOn;

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }
    
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
    
    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
    
    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    
    public String getMail() {
        return mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }
    
    public Date getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }
    
    public Date getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }
    
    @Override
    public String toString() {
        return MoreObjects.toStringHelper("User")
            .add("userId",  userId)
            .add("username",  username)
            .add("nickname",  nickname)
            .add("mobile",  mobile)
            .add("mail",  mail)
            .add("createdOn",  createdOn)
            .add("updatedOn",  updatedOn)
           .toString();
    }

    @Override
    public List<String> fields() {
      return Lists.newArrayList("userId",
						"username",
						"nickname",
						"mobile",
						"mail",
						"createdOn",
						"updatedOn");
    }
    
    public List<String> virtualFields() {
        return Lists.newArrayList("createdOn",
						"updatedOn");
    }
    
    @Override
    public String primaryField() {
        return "userId";
    }

    @Override
    public Long id () {
    return userId;
    }

    @Override
    public void setId(Long id) {
        this.userId = id;
    }

    @Override
    public void setGeneratedKey(Number key) {
    
        this.userId = key.longValue();
    
    }

    @Override
    public Map<String, Object> toMap() {
        Map<String, Object> map = Maps.newHashMap();
        map.put("userId",  userId);
        map.put("username",  username);
        map.put("nickname",  nickname);
        map.put("mobile",  mobile);
        map.put("mail",  mail);
        map.put("createdOn",  createdOn);
        map.put("updatedOn",  updatedOn);
        return map;
    }

    @Override
    public void fromMap(Map<String, Object> map) {
        if (map == null) {
            return;
        }
        if (map.get("userId") instanceof Long) {
            this.userId = (Long) map.get("userId");
        }
        if (map.get("username") instanceof String) {
            this.username = (String) map.get("username");
        }
        if (map.get("nickname") instanceof String) {
            this.nickname = (String) map.get("nickname");
        }
        if (map.get("mobile") instanceof String) {
            this.mobile = (String) map.get("mobile");
        }
        if (map.get("mail") instanceof String) {
            this.mail = (String) map.get("mail");
        }
        if (map.get("createdOn") instanceof Date) {
            this.createdOn = (Date) map.get("createdOn");
        }
        if (map.get("updatedOn") instanceof Date) {
            this.updatedOn = (Date) map.get("updatedOn");
        }
        
    }

   /* START Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
	/* END Do not remove/edit this line. CodeGenerator will preserve any code between start and end tags.*/
}